apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-converter-deployment
  namespace: video-to-audio-converter
spec:
  selector:
    matchLabels:
      app: gateway-converter

  replicas: 2
  template:
    metadata:
      labels:
        app: gateway-converter
    spec:
      containers:
      - name: gateway-converter
        image: gabzsz/gateway-converter:0.1.0
        ports:
        - containerPort: 80

